-- 1st Solution
SELECT ROUND(MIN(LONG_W), 4)
FROM STATION
WHERE LAT_N = (SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.7780);

-- 2nd Solution
SELECT ROUND(long_w, 4)
FROM STATION
WHERE lat_n > 38.7780
ORDER BY lat_n ASC
LIMIT 1;